### ISSUE TITLE
ORA-12547: TNS:lost contact

### ISSUE THREAD

**Issue by agaddale** [MaksymBilenko/docker-oracle-xe-11g#10]
Hi,

I am getting this error, when i try to login to sqlplus

docker exec -it a673fd18addc bash
root@a673fd18addc:/# sqlplus system/oracle

SQL*Plus: Release 11.2.0.2.0 Production on Wed Feb 17 11:52:00 2016

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

ERROR:
ORA-12547: TNS:lost contact

Enter user-name:

**Comment by MaksymBilenko** [comment]
@agaddale system/oracle should be logged in as sysdba
try to do this:
`sqlplus sys/oracle as sysdba`

**Comment by agaddale** [comment]
Thanks for the help.

Able to connect now.
