### ISSUE TITLE
Mounted datafile is not getting picked up by the database

### ISSUE THREAD

**Issue by agaddale** [MaksymBilenko/docker-oracle-xe-11g#11]
HI,

When i run the container using this below command 

docker run -d -p 8080:8080 -p 1521:1521 -v /Users/agaddale/Docker/ssue_oracle_db_files/dbf_files/SSUE:/u01/app/oracle -e processes=1000 -e sessions=1105 -e transactions=1215 sath89/oracle-xe-11g

I see that the instance XE is not using the database files that are there in the location '/Users/agaddale/Docker/ssue_oracle_db_files/dbf_files/SSUE'.

And hence i don't see my data objects in XE.

Can somebody tell what is that i am missing here.

**Comment by MaksymBilenko** [comment]
There might me an issues with mounted data cause of:
docker/docker#7198
What Host OS are you using?
Also would be nice to get container logs

**Comment by agaddale** [comment]
I am using OS X EI Captain.

I see that my dbf files have been copied to /u01/app/oracle, but when connected to this instance i still don't see my schema & tables.

![image](https://cloud.githubusercontent.com/assets/12751264/13111495/14f592ae-d5ac-11e5-9a67-26109b330279.png)


Below is the container logs for your reference.

![image](https://cloud.githubusercontent.com/assets/12751264/13111529/3fb81430-d5ac-11e5-8a68-686d7257aab2.png)

**Comment by MaksymBilenko** [comment]
double check owner and group of this folder.
oracle user in container should have rw access

**Comment by MaksymBilenko** [comment]
I remember that I had same issue on OS X. just check and fix permissions, then start db

**Comment by agaddale** [comment]
I tried changing the permissions where my datafiles were in my local machine, after which i see the following in my docker container logs.

docker-oracle-xe-11g-sa-master agaddale$ docker logs 233af117f2b8
Database not initialized. Initializing database.
Setting up:
processes=1000
sessions=1105
transactions=1215
If you want to use different parameters set processes, sessions, transactions env variables and consider this formula:
processes=x
sessions=x*1.1+5
transactions=sessions*1.1
ls: cannot access /u01/app/oracle/oradata: No such file or directory

Oracle Database 11g Express Edition Configuration
-------------------------------------------------
This will configure on-boot properties of Oracle Database 11g Express 
Edition.  The following questions will determine whether the database should 
be starting upon system boot, the ports it will use, and the passwords that 
will be used for database accounts.  Press <Enter> to accept the defaults. 
Ctrl-C will abort.

Specify the HTTP port that will be used for Oracle Application Express [8080]:
Specify a port that will be used for the database listener [1521]:
Specify a password to be used for database accounts.  Note that the same
password will be used for SYS and SYSTEM.  Oracle recommends the use of 
different passwords for each database account.  This can be done after 
initial configuration:
Confirm the password:

Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:
Starting Oracle Net Listener...Done

As per the logs i see one error w.r.t /u01/app/oracle/oradata, but when checked in the container the directory did exists.

root@233af117f2b8:/# cd /u01/app/oracle/oradata
root@233af117f2b8:/u01/app/oracle/oradata# ls
XE
root@233af117f2b8:/u01/app/oracle/oradata# cd ../
root@233af117f2b8:/u01/app/oracle# ls
SSUE_APP2_DATA.dbf  SSUE_LCM_DATA.dbf  admin  dbs  diag  fast_recovery_area  oradata  oradiag_oracle  product
root@233af117f2b8:/u01/app/oracle# ls -l
total 102420
-rwxrwxrwx 1 oracle staff 52436992 Feb 17 05:55 SSUE_APP2_DATA.dbf
-rwxrwxrwx 1 oracle staff 52436992 Feb 17 05:55 SSUE_LCM_DATA.dbf
drwxr-xr-x 1 oracle staff      136 Feb 17 14:09 admin
drwxr-xr-x 1 oracle staff      238 Feb 17 14:10 dbs
drwxr-xr-x 1 oracle staff      136 Feb 17 14:09 diag
drwxr-xr-x 1 oracle staff      102 Feb 17 14:09 fast_recovery_area
drwxr-xr-x 1 oracle staff      102 Feb 17 14:09 oradata
drwxr-xr-x 1 oracle staff      102 Feb 17 14:09 oradiag_oracle
lrwxr-xr-x 1 oracle staff       23 Feb 17 14:09 product -> /u01/app/oracle-product


And when exec this SQL 'SELECT NAME,
    FILE#,
    STATUS,
    CHECKPOINT_CHANGE# "CHECKPOINT"   
  FROM   V$DATAFILE;'

I still dont see my dbf file entry.

![image](https://cloud.githubusercontent.com/assets/12751264/13111994/fbd9c8fa-d5ae-11e5-9b7c-47e30a2c4187.png)

**Comment by MaksymBilenko** [comment]
@agaddale seems like you need to create/link your DB file.
Your installation seems fresh without any additional db data

**Comment by agaddale** [comment]
Hi MaksymBilenko,

I have created the DB files, and placed it in '/Users/agaddale/Docker/ssue_oracle_db_files/dbf_files/SSUE', which i am referring for the volumes attribute in the docker run command.

"_docker run -d -p 8080:8080 -p 1521:1521 -v /Users/agaddale/Docker/ssue_oracle_db_files/dbf_files/SSUE:/u01/app/oracle -e processes=1000 -e sessions=1105 -e transactions=1215 sath89/oracle-xe-11g_"

Is this the right way to link database files?

Thanks,
Aarthi G

**Comment by MaksymBilenko** [comment]
@agaddale Yes you doing this right.
But it seems like oracle DB doesn't know about your custom db files.
Go to the apex console and check the list. I'm not sure what is the right way to link them to your installation.
Here is some discussions about this issue:
https://community.oracle.com/thread/271040?start=0&tstart=0

**Comment by agaddale** [comment]
The below image(based on your image) helped me to create a sample database with initialisation scripts.

https://github.com/SirRagnar/rgt-oracle-xe-11g

Thanks a lot Maksym Bilenko for your help!

**Comment by MaksymBilenko** [comment]
You are welcome
