### ISSUE TITLE
%hosename% and %port% found in tnsnames.ora

### ISSUE THREAD

**Issue by zlcolin** [MaksymBilenko/docker-oracle-xe-11g#13]
%hosename% and %port% found in tnsnames.ora, it's perfect if like listener.ora
root@c548af6660cf:/u01/app/oracle/product/11.2.0/xe/network/admin# cat tnsnames.ora
```
# tnsnames.ora Network Configuration File:
XE =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = %hostname%)(PORT = %port%))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = XE)
    )
  )
EXTPROC_CONNECTION_DATA =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC_FOR_XE))
    )
    (CONNECT_DATA =
      (SID = PLSExtProc)
      (PRESENTATION = RO)
    )
  )
```

**Comment by MaksymBilenko** [comment]
Hello @zlcolin  those placeholders are replacing on database startup when you start via [entrypoint.sh](https://github.com/MaksymBilenko/docker-oracle-xe-11g/blob/master/entrypoint.sh)
or via init.d script.
When you start container with shell there is a hint:
`Database is not configured. Please run /etc/init.d/oracle-xe configure if needed.`
After running this - you would have inited database and configured tnsnames.ora
It would also work if you would mount database files
