### ISSUE TITLE
Errors on file creation

### ISSUE THREAD

**Issue by vertigo7x** [MaksymBilenko/docker-oracle-xe-11g#14]
Hi, im facing several errors when trying to use the container with data persisted on the host. With this run command:

docker run -t -d -p 8080:8080 -p 1521:1521 -v /c/Users/USER/DATA/:/u01/app/oracle sath89/oracle-xe-11g

I get the following log:

https://gist.github.com/vertigo7x/0931117a5baa83b501a1f69dd6b5a50e

Not sure if the problem is related to the image or with docker.

Thanks in advance!

PS: Im using Windows 7 with docker-toolbox 1.11

PS2: Inspect file added to Gist: https://gist.github.com/vertigo7x/22bec10a9bc3e526e65953a6a6281dad

**Comment by vertigo7x** [comment]
Ok, nevermind, just give the shell Admin rights and it worked flawlessly

**Comment by MaksymBilenko** [comment]
Hello @vertigo7x 
There might me an issues with mounted data cause of:
https://github.com/docker/docker/issues/7198

There is a permissions issue with using of windows mounted folders
Try to create some VM storage for your docker VM and put oracle data there

**Comment by MaksymBilenko** [comment]
@vertigo7x 
Hm,
Could you please describe a bit more about admin rights to the shell?

**Comment by vertigo7x** [comment]
Hi @MaksymBilenko !

Sadly I must admit that I was been able to make it work almost once, because now I'm facing other problems. I cant connect to the container ports after restarting the container.

In the permissions side, I just opened up the Docker QuickStart Terminal as Administrator and then the volume and all Oracle data files were created without any problem. I was able to connect to the ports too. But now, I cant access even port 8080 or 1521.

**Comment by MaksymBilenko** [comment]
@vertigo7x 
Yeah that seems like permissions issue, cause of Windows unable to see those permissions an they must be flushed after restart.
The easiest way for you would be to create additional storage and store database files there, the main thing is not to use windows volumes
