### ISSUE TITLE
ORA-12547: TNS:lost contact

### ISSUE THREAD

**Issue by heron182** [MaksymBilenko/docker-oracle-xe-11g#15]
After configuring my db (tables, schemas etc) and generating a new image via docker commit i am not able to connect to the database when running a container from my new image.

I get a ORA-12547: TNS:lost contact , even if trying to connect as sysdba.

Any tips on that error ?

**Comment by heron182** [comment]
**update**

Tested with 2 images, same 2 commands:

docker pull sath89/oracle-xe-11g
docker pull alexeiled/docker-oracle-xe-11g

docker run -d -p 1521:1521 imageid 

docker commit imagedid somename

docker run -d -p 1521:1521 newimageid

docker exec -it newconatinerid bash

sqlplus / as sysdba

**sath89/oracle-xe-11g as base image: ORA-12547: TNS:lost contact**
**alexeiled/docker-oracle-xe-11g as base image: Connect successful**

**Comment by heron182** [comment]
Ok, for anyone who´s interested:
The problem is with the dockerfile mounting the oracle data folder
VOLUME "/u01/app/oracle"

When i commit my container, this folder is not saved into my new image, generating the errors to start the db.

**Comment by MaksymBilenko** [comment]
Hello @heron182  This image is not designed for container commits.
If you would like to use this image for commiting it - you would need to rebuild Dockerfile without Volume
