### ISSUE TITLE
update SID and SYSTEM Password  for oracle 11g

### ISSUE THREAD

**Issue by joroslim** [MaksymBilenko/docker-oracle-xe-11g#17]
hi i want to update your image to new SID name system password . 

tried committing the your image, and im having problems with connect to sid . 

im new to this. 
please guide me. thanks

**Comment by joroslim** [comment]
https://github.com/MaksymBilenko/docker-oracle-xe-11g

i downloaded this as zip 

modify Dockerfile 
ENV ORACLE_SID=TESTSID  

cant find where should i change for the default  system password

**Comment by joroslim** [comment]
this happens when i accessed the container , the one that i build

docker@default:~$ docker exec -it 5646d1982c0a /bin/bash
root@5646d1982c0a:/# sqlplus

SQL*Plus: Release 11.2.0.2.0 Production on Wed Aug 10 12:32:40 2016

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

Enter user-name: system
Enter password:
ERROR:
ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory
Process ID: 0
Session ID: 0 Serial number: 0


Enter user-name:

**Comment by MaksymBilenko** [comment]
@joroslim I think you need to modify this 2 files as well:
https://github.com/MaksymBilenko/docker-oracle-xe-11g/blob/master/init.ora
https://github.com/MaksymBilenko/docker-oracle-xe-11g/blob/master/initXETemp.ora
