### ISSUE TITLE
Connection via sql developer to docker image on EC2 AWS

### ISSUE THREAD

**Issue by DvirLevanon** [MaksymBilenko/docker-oracle-xe-11g#20]
1521 port is open on security policy and mapped from docker
5bdf90c96f62        sath89/oracle-xe-11g   "/entrypoint.sh "        21 minutes ago      Up 21 minutes       0.0.0.0:1521->1521/tcp, 0.0.0.0:8010->8080/tcp 

enable to connect via sqlplus inside the container, get connection timeout from sql developer

**Comment by MaksymBilenko** [comment]
Hello @DvirLevanon,
If you having connection timeout error, than it's not related to the docker image. Double check your security groups and etc...

**Comment by wieta** [comment]
Hi, 
I have problem with connection via host ip. In my application when I type host ip in connection string i have lag for 30 until get the data from db. When i type container ip in my connection string it's work well. Any sugestions to fix that ?

**Comment by MaksymBilenko** [comment]
Hi, @wieta,
Probably your issue is related to docker installation.
Could you check accessibility of some other app via host ip?
Are you sure that this issue is related to the database container?
If issue is only with database, could you please provide your host info (OS, docker version, type, etc)

**Comment by wieta** [comment]
Yes i have access to other app, i thin that's some problem with network dns maybe. Thiss issue is on my client os and machine(Debian 8, docker 1.12.3). I check on my test machine(virtualbox) with ubuntu and via host ip i have 3 sec lag during starting my app but then read data works well.

**Comment by MaksymBilenko** [comment]
@wieta ,
I'll try to reproduce this bug and I'll see what could be done,
Could you please update this if you would find a fix.
Cheers

**Comment by wieta** [comment]
I check traceroute to container ip on my client machine and as I thought 30 seconds wait for trace output. On my ubuntu virutal i have immediately output. Interesting trip time is very small but on client machine i wait 30 sec for output. I'm pretty sure it's issue with network but i don't why after change ip in connection string db works well

`  172.17.0.2 (172.17.0.2)  0.085 ms  0.023 ms  0.017 ms -> client `
   `172.17.0.2 (172.17.0.2)  0.038 ms  0.009 ms  -> virtualbox`

**Comment by wieta** [comment]
Hi, 
I fixed my issue :) Problem was with dns setting at /etc/defaul/docker. I add correct dns and important in my resolv.conf i have define search local domain and in ../docker i must type '--dns-search' and everything works fine form me with host ip in my connection string to db `DOCKER_OPTS="--dns-search domain_name --dns 8.8.8.8" `
Cheers

**Comment by MaksymBilenko** [comment]
@wieta,
Ok, that's nice, thank you.
