### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by shanethehat** [MaksymBilenko/docker-oracle-xe-11g#21]
Please could you tag releases in Dockerhub so that we can fix our build process to a known version of the container?

**Comment by MaksymBilenko** [comment]
@shanethehat What kind of tag? oracle version or what?

**Comment by shanethehat** [comment]
I meant like a numeric tag rather than only using `latest`, so that in our Dockerfile we can have do `FROM <image>:<tag>`

**Comment by MaksymBilenko** [comment]
@shanethehat why do you need that? version are not going to change. So Why you don't just use latest?

**Comment by ksylvan** [comment]
Oracle version tags would be good. 11.2.0.2.0 for the current latest, and other tags for other version images (11.2.0.4.0, etc.)

**Comment by scav** [comment]
👍 

This is very important in case a change introduces something breaking the current image. Building on :latest basically means we lose all control.

**Comment by MaksymBilenko** [comment]
I'm not planning to perform any changes in this repo. But in case of any inc changes I'll do tags
