### ISSUE TITLE
Disable account auto locking

### ISSUE THREAD

**Issue by zedtux** [MaksymBilenko/docker-oracle-xe-11g#23]
Thank you @MaksymBilenko for this really awesome Docker image. I never worked with an Oracle database, and it's really painful *just* to import a dump file, but thanks to your magic image, I'm able to do imports 👍.

Now, I have an issue to connect to the DB, and after a few tried I got the following error:

```
ORA-28000: the account is locked
```

It looks like [it's possible to disable (or increase the amount of tries) the auto locking](http://stackoverflow.com/a/26859212/1996540).

Could you please add this? (Maybe with an env variable to do it or not so that we can have the best of both worlds?)

Again: THANK YOU!

**Comment by zedtux** [comment]
So what @MaksymBilenko ?

**Comment by MaksymBilenko** [comment]
@zedtux you can go to
```
docker exec -it container_name /bin/bash
su oracle
$ORACLE_HOME/bin/sqlplus / as sysdba
configure/disable limits or anything
```
