### ISSUE TITLE
Oracle won't start if i use some command

### ISSUE THREAD

**Issue by angeloveiga31** [MaksymBilenko/docker-oracle-xe-11g#25]

**Comment by angeloveiga31** [comment]
When I use 

docker run -d -p 8080:8080 -p 1521:1521 -v /my/oracle/data:/u01/app/oracle sath89/oracle-xe-11g

with the dbf files in \my\oracle\data\oradata\XE

i get this message on docker container:

found files in /u01/app/oracle/oradata Using them instead of initial database
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.
2017-03-09T10:28:06.389521300Z 
[IMPORT] Not a first start, SKIPPING Import from Volume '/docker-entrypoint-initdb.d'
[IMPORT] If you want to enable import at any state - add 'IMPORT_FROM_VOLUME=true' variable
2017-03-09T10:28:06.400302500Z 
Database ready to use. Enjoy! ;)

and then i cannot connect the Oracle XE

My files have 6 Gb's of size

can you help me?

**Comment by MaksymBilenko** [comment]
Try to start manually
```su oracle
sqlplus / as sysdba
startup;
```
