### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by cyratech** [MaksymBilenko/docker-oracle-xe-11g#26]
unable to log into the url http://localhost:8080/apex  using provided credentials .
message : "Invalid Login Credentials"

**Comment by MaksymBilenko** [comment]
Checked right now from latest image. Those works:
```
Connect to Oracle Application Express web management console with following settings:

    http://localhost:8080/apex
    workspace: INTERNAL
    user: ADMIN
    password: oracle
```

**Comment by okrad** [comment]
Hi @MaksymBilenko, I'm having the same issue here. 

Apex keeps telling me the credentials are not valid:
![image](https://user-images.githubusercontent.com/939812/28358410-0aad2022-6c6f-11e7-84a1-85cb6724d509.png)

Do you have any suggestions?

Thank you

**Comment by MaksymBilenko** [comment]
@okrad have you recently changed password?
On first login apex ask you to change password...

**Comment by okrad** [comment]
No, I just started the container for the first time. Apex isn't asking me to change password.
