### ISSUE TITLE
How to update this to 11.2.0.4.0?

### ISSUE THREAD

**Issue by ksylvan** [MaksymBilenko/docker-oracle-xe-11g#27]
The current image is 11.2.0.2.0 and it looks like you have a set of files that are the result of running split on the `.deb` of the oracle installer file. Can you update it to 11.2.0.4.0? It would also be easy to add some tags to the docker hub images corresponding to the versions.

Thanks for this image, it's very useful!

**Comment by MaksymBilenko** [comment]
@ksylvan I've forked this repo, you might ask for upgrade at the initial project
