### ISSUE TITLE
ORA-01031: insufficient privileges

### ISSUE THREAD

**Issue by xuhj** [MaksymBilenko/docker-oracle-xe-11g#29]
![Uploading image.png…]()
root@7aa0609ac215:/# sqlplus /nolog
SQL*Plus: Release 11.2.0.2.0 Production on Wed Jun 21 08:32:34 2017

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

SQL> connect / as sysdba
ERROR:
ORA-01031: insufficient privileges

SQL>

can you help me?

**Comment by wieta** [comment]
Did you tryed: 
`connect sys as sysdba` pass: oracle
`connect system` pass: oracle 
work for me 
But `connect / as sysdba` also have "ORA-01031"

**Comment by xuhj** [comment]
@wieta 
SQL> connect sys as sysdba
Enter password:
ERROR:
ORA-01031: insufficient privileges


SQL> connect system
Enter password:
ERROR:
ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory
Process ID: 0
Session ID: 0 Serial number: 0


SQL>

**Comment by wieta** [comment]
when u check logs `docker logs container_name` do u have something like "
Database ready to use. Enjoy! ;)" ?

**Comment by xuhj** [comment]
logs:
found files in /u01/app/oracle/oradata Using them instead of initial database
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.

[IMPORT] Not a first start, SKIPPING Import from Volume '/docker-entrypoint-initdb.d'
[IMPORT] If you want to enable import at any state - add 'IMPORT_FROM_VOLUME=true' variable

Database ready to use. Enjoy! ;)
Shutting down Oracle Database 11g Express Edition instance.
Stopping Oracle Net Listener.

found files in /u01/app/oracle/oradata Using them instead of initial database
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.

[IMPORT] Not a first start, SKIPPING Import from Volume '/docker-entrypoint-initdb.d'
[IMPORT] If you want to enable import at any state - add 'IMPORT_FROM_VOLUME=true' variable

Database ready to use. Enjoy! ;)

**Comment by xuhj** [comment]
@wieta

**Comment by xuhj** [comment]
@wieta 
logs:
found files in /u01/app/oracle/oradata Using them instead of initial database
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.

[IMPORT] Not a first start, SKIPPING Import from Volume '/docker-entrypoint-initdb.d'
[IMPORT] If you want to enable import at any state - add 'IMPORT_FROM_VOLUME=true' variable

Database ready to use. Enjoy! ;)
Shutting down Oracle Database 11g Express Edition instance.
Stopping Oracle Net Listener.

found files in /u01/app/oracle/oradata Using them instead of initial database
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.

[IMPORT] Not a first start, SKIPPING Import from Volume '/docker-entrypoint-initdb.d'
[IMPORT] If you want to enable import at any state - add 'IMPORT_FROM_VOLUME=true' variable

Database ready to use. Enjoy! ;)

**Comment by wieta** [comment]
So i don't know, i rebuild image and it work for me. I saw that somebody has similar problem https://github.com/MaksymBilenko/docker-oracle-xe-11g/issues/17

**Comment by MaksymBilenko** [comment]
To login as sys without password you need to `su oracle` first
