### ISSUE TITLE
How to run sqlplus while building a new image from yours

### ISSUE THREAD

**Issue by SirRagnar** [MaksymBilenko/docker-oracle-xe-11g#3]
Hi.

First thanks for this (thin) docker image.

I want to make a Docker image that extends docker-oracle-xe-11g. Aditionally to your image i want my image to clone some scripts under one of my repos and finally I want to unlock HR account. I want to use that image for some experiments and it would be useful for to to have HR account unlocked on startup.

This is a link to my [Dockerfile](https://github.com/SirRagnar/compose-nodejs-oraclexe/blob/9343b1979eb91b43e84fdac624441e96b725b133/images/oracle-xe/Dockerfile).

When i run the build this is the output (i remove all output related to git installation because it is irrelevant for this issue):

```
Step 0 : FROM sath89/oracle-xe-11g:latest
 ---> 2c83b63b204f
Step 1 : RUN apt-get -y update && apt-get install -y git
 ---> Running in e99099f080eb
 ...
 ---> 6497f6473194
Removing intermediate container e99099f080eb
Step 2 : RUN mkdir /u01/scripts
 ---> Running in ca8462b0aedc
 ---> abcbe836f3a6
Removing intermediate container ca8462b0aedc
Step 3 : RUN git clone https://github.com/SirRagnar/sqlPlusToolBox.git /u01/scripts
 ---> Running in 741e743e24af
Cloning into '/u01/scripts'...
 ---> f47c47a9f409
Removing intermediate container 741e743e24af
Step 4 : RUN mkdir /u01/scripts/init
 ---> Running in 5d4d3f2c9998
 ---> e8faa48ba9d1
Removing intermediate container 5d4d3f2c9998
Step 5 : COPY unlockhr.* /u01/scripts/init/
 ---> 2d2a3a1c2fbe
Removing intermediate container fcfa3eef7f01
Step 6 : RUN chmod +x /u01/scripts/init/unlockhr.sh
 ---> Running in cffd64bb3ed5
 ---> c98358edb596
Removing intermediate container cffd64bb3ed5
Step 7 : RUN /u01/scripts/init/unlockhr.sh
 ---> Running in 1640209aa3be
unlocking hr account
-su: /u01/app/oracle/product/11.2.0/xe/bin/sqlplus: No such file or directory
```
The shell script simply does this:

```bash
#!/bin/bash
echo unlocking hr account
/bin/su - oracle -c "$ORACLE_HOME/bin/sqlplus -S system/oracle @/u01/scripts/init/unlockhr.sql"
```
As you can see the build failed with `/u01/app/oracle/product/11.2.0/xe/bin/sqlplus: No such file or directory`.

It seems that because of the ["ln -f" at the begining of your entrypoint](https://github.com/MaksymBilenko/docker-oracle-xe-11g/blob/2291d75a76a5ca144689827d793a7d73c7924e29/entrypoint.sh#L6) the shell script is unable to find sqlplus. I've tryed to call _sqlplus_ with a `RUN` with the same result.

It seems that while building the image the path `/u01/app/product' is unreacheable. I've started a container of your image and exec a bin/bash inside it and I've executed sqlplus normally without trouble.

Do you know how could i avoid this error?

Thanks in advance

**Comment by MaksymBilenko** [comment]
The issue seem's like because you trying to run script before database were initialized.
Database initialization begins when you starting container (if initialize database on the docker build step - that's + ~1.5Gb of image size and cause issues for database file mount support).
Assuming best practices - I believe that the best way for you would be to create lightweight image with sqlplus client and run it with your queries against your oracle container.

**Comment by SirRagnar** [comment]
That's it!
I'll do it as you suggest.

Thanks for your response.

**Comment by MaksymBilenko** [comment]
Good luck with this.
I would be appreciate if you would post link to your working image here.
Cheers

**Comment by MaksymBilenko** [comment]
Also, I believe this might be helpful for you:
https://github.com/webdizz/docker-oracle-xe-11g-sa

**Comment by SirRagnar** [comment]
Yes, that's just what i'm looking for.

Thanks!

**Comment by SirRagnar** [comment]
Hi @MaksymBilenko, finally I finished the first version of my image: [carloscastillo/rgt-oracle-xe-11g](https://hub.docker.com/r/carloscastillo/rgt-oracle-xe-11g/)

Thanks very much for your support and for your suggestions.
