### ISSUE TITLE
Change default sys/system password

### ISSUE THREAD

**Issue by atecey** [MaksymBilenko/docker-oracle-xe-11g#31]
Can the sys & system password be set in some of the configuration files or passed in as an env variable?

**Comment by MaksymBilenko** [comment]
@atecey, yes,
You could prepare sql file with change sys/system passwords queue:
echo 'alter user sys identified by <password>;' > sys_pass.sql
echo 'alter user system identified by <password>;' >> sys_pass.sql

`docker run ... -v '$PWD:/docker-entrypoint-initdb.d' ...`

**Comment by atecey** [comment]
Is there a way to build it into the Docker build process.  I've created a setup.sql script to change a few params on startup

`ALTER USER sys IDENTIFIED BY "admin";
ALTER USER system IDENTIFIED BY "admin";
ALTER SYSTEM DISABLE RESTRICTED SESSION
ALTER SYSTEM SET disk_asynch_io = FALSE SCOPE = SPFILE;
ALTER TABLESPACE system ADD DATAFILE '/u01/app/oracle/oradata/XE/system1.dbf' SIZE 1024M AUTOEXTEND ON NEXT 512K MAXSIZE 4096M;`

I added it to the dockerfile and then moved it into the entrypoint location inside 
`FROM ubuntu:14.04

# get rid of the message: "debconf: unable to initialize frontend: Dialog"
ENV DEBIAN_FRONTEND noninteractive

ADD chkconfig /sbin/chkconfig
ADD oracle-install.sh /oracle-install.sh
ADD init.ora /
ADD initXETemp.ora /
ADD setup.sql /
ADD oracle-xe.part1 /oracle-xe_11.2.0-1.0_amd64.debaa
ADD oracle-xe.part2 /oracle-xe_11.2.0-1.0_amd64.debab
ADD oracle-xe.part3 /oracle-xe_11.2.0-1.0_amd64.debac

# Prepare to install Oracle
RUN apt-get update && apt-get install -y -q libaio1 net-tools bc curl rlwrap && \
apt-get clean && \
rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/* &&\
ln -s /usr/bin/awk /bin/awk &&\
mkdir /var/lock/subsys &&\
chmod 755 /sbin/chkconfig &&\
/oracle-install.sh

# see issue #1
ENV ORACLE_HOME /u01/app/oracle/product/11.2.0/xe
ENV PATH $ORACLE_HOME/bin:$PATH
ENV ORACLE_SID=XE

EXPOSE 1521
EXPOSE 8080
VOLUME ["/u01/app/oracle"]

ENV processes 500
ENV sessions 555
ENV transactions 610

ADD entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
CMD [""]

`

And modified the oracle-install.sh
`#!/bin/bash

ORA_DEB="oracle-xe_11.2.0-1.0_amd64.deb"

#
# download the Oracle installer
#
downloadOracle () {

	local ora_deb_partial=( 
		${ORA_DEB}aa 
		${ORA_DEB}ab 
		${ORA_DEB}ac
	)

	cat /${ORA_DEB}a* > /${ORA_DEB}

	rm -f /${ORA_DEB}a*

}

downloadOracle

dpkg --install /${ORA_DEB}
rm -f /${ORA_DEB}

mv /init.ora       /u01/app/oracle/product/11.2.0/xe/config/scripts
mv /initXETemp.ora /u01/app/oracle/product/11.2.0/xe/config/scripts

mv /u01/app/oracle/product /u01/app/oracle-product

mv /setup.sql /docker-entrypoint-initdb.d

apt-get clean && rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*
`

The image builds and runs but the setup.sql does not seem to have run.  This is the output 
`Database not initialized. Initializing database.
Setting up:
processes=500
sessions=555
transactions=610
If you want to use different parameters set processes, sessions, transactions env variables and consider this formula:
processes=x
sessions=x*1.1+5
transactions=sessions*1.1

Oracle Database 11g Express Edition Configuration
-------------------------------------------------
This will configure on-boot properties of Oracle Database 11g Express
Edition.  The following questions will determine whether the database should
be starting upon system boot, the ports it will use, and the passwords that
will be used for database accounts.  Press <Enter> to accept the defaults.
Ctrl-C will abort.

Specify the HTTP port that will be used for Oracle Application Express [8080]:
Specify a port that will be used for the database listener [1521]:
Specify a password to be used for database accounts.  Note that the same
password will be used for SYS and SYSTEM.  Oracle recommends the use of
different passwords for each database account.  This can be done after
initial configuration:
Confirm the password:

Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:
Starting Oracle Net Listener...Done
Configuring database...Done
Starting Oracle Database 11g Express Edition instance...Done
Installation completed successfully.
Database initialized. Please visit http://#containeer:8080/apex to proceed with configuration
Oracle Database 11g Express Edition instance is already started

Starting import scripts from '/docker-entrypoint-initdb.d':
/entrypoint.sh: line 105: /docker-entrypoint-initdb.d/.cache: Not a directory
/entrypoint.sh: line 106: /docker-entrypoint-initdb.d/.cache: Not a directory
/entrypoint.sh: line 107: /docker-entrypoint-initdb.d/.cache: Not a directory
Import finished`

In case you're wondering why I have to do it this way,  the laptop I am running on has a firewall set by group policy that doesn't allow docker access to the C/D/E drives so mounting a volume is not possible.  Plus it would be better for me to make these changes so other can just pull the image internally and use it without having to create their own setup.sql

**Comment by MaksymBilenko** [comment]
I'll see what could be done once I'll have some time for this.
Anyways open for PR's like modify DBCA init line with using ENV_VARIABLES like SYS_PASSWORD

**Comment by MaksymBilenko** [comment]
@atecey I was wrong. you need to take a look on line:

**Comment by MaksymBilenko** [comment]
`docker run -d -p 8080:8080 -p 1521:1521 -e DEFAULT_SYS_PASS=sYs-p@ssw0rd sath89/oracle-xe-11g`
This would set sys password on DB init phase. anyways, not sure that it is safe for real passwords...

**Comment by MaksymBilenko** [comment]
@MaksymBilenko Please test and update this issue.

**Comment by atecey** [comment]
Tried it for both sys and system users and get the following error for both

```
Enter user-name: sys
Enter password: admin
ERROR:
ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory
Process ID: 0
Session ID: 0 Serial number: 0
```

This is the command i used to start it
`docker run -d -p 8080:8080 -p 1521:1521 -e DEFAULT_SYS_PASS=admin -e processes=1000 -e sessions=1105 -e transactions=1215 sath89/oracle-xe-11g`

**Comment by MaksymBilenko** [comment]
@atecey Let me check

**Comment by MaksymBilenko** [comment]
@atecey looks like this is a bug in init.d script that are inside of deb package...

**Comment by MaksymBilenko** [comment]
@atecey Fixed by workaround,
Pull image and test

**Comment by MaksymBilenko** [comment]
https://asciinema.org/a/dsQLOM7iuyd6THLDiW7lyEWHm
