### ISSUE TITLE
Data volume cannot be persisted

### ISSUE THREAD

**Issue by cc-man** [MaksymBilenko/docker-oracle-xe-11g#36]
1., I found in the process of using the mirror in different hosts on the database will not be able to persistent problems, such as: Ubuntu 16.04, server version is good, but sometimes in centOS 7 sometimes wrong. I felt puzzled
2. there will be errors when starting Oracle: mv: cannot remove'/u01/app/oracle-product/11.2.0/xe/dbs': Directory not empty"

**Comment by MaksymBilenko** [comment]
Sounds like Docker on CentOS storage driver issue.
Try to Google for alternative docker storage drivers for centos kernel.
