### ISSUE TITLE
Mount Volume is not working

### ISSUE THREAD

**Issue by vasanth-mahendran** [MaksymBilenko/docker-oracle-xe-11g#37]
Hi,

I copied the Oracle directory(/u01/app/oracle) from an environment where XE is working fine into D:\data\oracle-xe

I ran the container with below command
docker run -d -p 8080:8080 -p 1521:1521 -v D:\data\oracle-xe:/u01/app/oracle sath89/oracle-xe-11g

I got the below error in the container startup logs
rm: cannot remove '/u01/app/oracle/product': Is a directory
ln: failed to create symbolic link '/u01/app/oracle/product/oracle-product': File exists

After that, it says "Database ready to use. Enjoy! ;)" but I couldn't able to connect to the Oracle XE it says "TNS listener does not currently know of SIS given in connect descriptor"

Any help would be much appreciated

**Comment by cc-man** [comment]
I also had the same problem, personal feelings and hard drives
And maybe there's not enough authority

**Comment by paulnuk** [comment]
Under Windows 7 at least, try placing your mounts in the logged on user's home' directory e.g. /c/Users/LoggedInUser

**Comment by vasanth-mahendran** [comment]
Thanks. Yes, it is related to permissions. Giving full permission solved the issue
