### ISSUE TITLE
ORA-01033

### ISSUE THREAD

**Issue by nishad27** [MaksymBilenko/docker-oracle-xe-11g#39]
# sqlplus

SQL*Plus: Release 11.2.0.2.0 Production on Fri Feb 2 05:45:30 2018

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

Enter user-name: sys
Enter password:
ERROR:
ORA-01033: ORACLE initialization or shutdown in progress
Process ID: 0
Session ID: 0 Serial number: 0

Enter user-name:

**Comment by mmd0308** [comment]
我也是这个问题，请问楼上解决了吗
