### ISSUE TITLE
Latest image not running

### ISSUE THREAD

**Issue by thomseno** [MaksymBilenko/docker-oracle-xe-11g#5]
Log stats: `Database is not configured. Please run /etc/init.d/oracle-xe configure if needed.`... and nothing happens!

Platform OSX. Docker 1.9.0, Kitematic 0.9.3

**Comment by thomseno** [comment]
Creating from command line (not Kitematic) works!

**Comment by MaksymBilenko** [comment]
Checking this issue

**Comment by MaksymBilenko** [comment]
Have you changed CMD in the Kitematic container?

**Comment by MaksymBilenko** [comment]
Seems like you getting this message when you running exec, but on real it should work fine. This message is in the entrypoint.sh and prompting only when you running exec

**Comment by MaksymBilenko** [comment]
I see the issue, working on that

**Comment by MaksymBilenko** [comment]
Fixed now, there is still an issue with logs. also there might me an issues with mounted data cause of:
https://github.com/docker/docker/issues/7198

**Comment by thomseno** [comment]
Thanks :thumbsup:
