### ISSUE TITLE
Docker image was deleted from Docker Hub

### ISSUE THREAD

**Issue by angrynaz** [MaksymBilenko/docker-oracle-xe-11g#51]

**Comment by Ldoppea** [comment]
Hi, I just discovered that issue. It is related to this reddit post : https://www.reddit.com/r/docker/comments/ail87k/my_image_with_10m_pulls_has_just_gone_completely/

I hope you'll find a solution so all your efforts won't be lost.

**Comment by MaksymBilenko** [comment]
Enabled auto build on quay.io
