### ISSUE TITLE
Updating Apex to Latest Version

### ISSUE THREAD

**Issue by mandaman2k** [MaksymBilenko/docker-oracle-xe-11g#6]
Hi,

I just came across your image, which is quite awsome, i just wanted to know if it is possible to update apex to the latest version?

I'm kind of new to all this docker stuff, i tried updating directly from the terminal but i wasn't possible.

Hope you could help me

Thank you

**Comment by MaksymBilenko** [comment]
Hello, 
I'll try to take a look at this, but right now at free time I'm working on oracle-12c here https://github.com/MaksymBilenko/docker-oracle-12c

**Comment by mandaman2k** [comment]
Ohh that is awesome, I didnt know 12c was open, keep up the awsome job

**Comment by MaksymBilenko** [comment]
Hm, I believe I need to do the same for 12c. I'm about to create Apex-Install docker image that would perform install/upgrade of apex

**Comment by MaksymBilenko** [comment]
Image for upgrading Apex is ready:
https://github.com/MaksymBilenko/docker-oracle-apex
You need to run this once per database installation (mounted db files).
Please create an issue in case of any issues ;)

**Comment by MaksymBilenko** [comment]
Let me know if it works well for you

**Comment by mandaman2k** [comment]
Hi,

I just got a chance to try it out and I just have to say, you are awesome, it worked like a charm,

Thank you very much

**Comment by MaksymBilenko** [comment]
You are welcome, If you have any suggestions for improvement, just open an issue.
Cheers
