### ISSUE TITLE
После запуска долгое время загрузка 100%

### ISSUE THREAD

**Issue by vlsergey-at-work** [MaksymBilenko/docker-oracle-xe-11g#7]
в момент первого чистого запуска загрузка CPU 100% на задаче:
/u01/app/oracle/product/11.2.0/xe/bin/sqlplus -s        @/u01/app/oracle/product/11.2.0/xe/config/scrip...

скорее всего идёт инициализация, но проверить статус не получается. На 1521 порт ни под SYS, ни под SYSTEM не заходит:
- SYS -- ORA-01017: invalid username/password; logon denied
- SYSDBA -- ORA-01031: insufficient privileges
- SYSTEM -- ORA-01031: insufficient privileges

можно как-то присоединиться к базе данных и проверить, что там действительно ещё идёт инициализация (целый час?), или же она повисла?

**Comment by vlsergey-at-work** [comment]
после "su - oracle" получилось из консоли зайти под "sqlplus / as sysdba". Однако попытка выполнить запрос даёт ошибку: ORA-01034: ORACLE not available

стоит ли пробовать сделать startup?

**Comment by MaksymBilenko** [comment]
Да, инициализация занимает некоторое время,
Оракл 12c сама по себе очень тяжелая, у меня на SSD, i7, 16Gb RAM - это занимает 2 минуты.
К сожелению я не смогу с этим ничего поделать - так как это уже механизмы самой Oracle DB. По статусу инициализации можно ужнать в логах контейнера.

Так-же, если вы используете внешний сторедж для базы - инициализация нужна только 1 раз, в дальнейшем старт будет очень быстрым

**Comment by vlsergey-at-work** [comment]
Использую внешний сторадж. Сторадж подготовил на одном компе (тоже через docker + oracle), запустить пытаюсь на втором. Висит в 100% CPU:

root@ubuntu:/home/developer# docker run -it -p 8080:8080 -p 1521:1521 -v /dev/shm:/dev/shm -v /run/shm:/run/shm -v /var/local/oracle:/u01/app/oracle -e processes=100 -e sessions=111 -e transactions=122 sath89/oracle-xe-11g               found files in /u01/app/oracle/oradata Using them instead of initial database
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.

Висит на:
root      1104  0.0  0.1  46632  2660 pts/2    S+   10:33   0:00 /bin/su -s /bin/bash oracle -c /u01/app/oracle/product/11.2.0/xe/bin/sqlplus -s /nolog @/u01/app/oracle/product/11.2.0/xe/config/scripts/startdb.sql
 1106 develop+  20   0  808072  43136  39960 R 100.0  1.7   9:03.03                      oracleXE (DESCRIPTION=(LOCAL=YES)(ADDRESS=(PROTOCOL=beq)))


с точно такой же строкой на другом компе, с другим процессором запускается... какие логи смотреть?

**Comment by MaksymBilenko** [comment]
А жесткий диск использовался тот-же?

**Comment by MaksymBilenko** [comment]
Закрыто по причине отсутствия ответа
