### ISSUE TITLE
couldn't start up oracle database after re-image

### ISSUE THREAD

**Issue by liuxiaopiao** [MaksymBilenko/docker-oracle-xe-11g#8]
I run the following commands: 
docker run -d -p 8080:8080 -p 1521:1521 sath89/oracle-xe-11g;
(The docker container id is ba8ad053939f)
docker commit -m "oracle xe" -a "anne" ba8ad053939f oracle/xe:v1 (without any changes) 
(The new image id is 71a3e3a0569b )
docker tag 71a3e3a0569b test98/oracle-xe:latest
Then run the command that:
docker run -d -p 8081:8080 -p 1522:1521 test98/oracle-xe:latest.

But the oracle database failed to startup in the container which created by my new docker image 71a3e3a0569b,

Is there anything I need to pay attention to when recreating new image with your image file?

Thank you very much!

**Comment by MaksymBilenko** [comment]
@liuxiaopiao Show me the logs please

**Comment by MaksymBilenko** [comment]
@liuxiaopiao Also I see that you used commit, and I must say that its not going to work cause of:
- Database has some functionality in /entrypoint.sh and changing database on startup
- Database files is on the Volume, so data is stored outside of container

**Comment by liuxiaopiao** [comment]
Thanks @MaksymBilenko  very much for the reply. So instead of commit command,  how can I create my own image on the basis of your image? I just want to upgrade apex to 4.2.6 version.

**Comment by MaksymBilenko** [comment]
@liuxiaopiao you can update apex by my other image:
https://github.com/MaksymBilenko/docker-oracle-apex
To do this just run:
```
docker run -it --rm --volumes-from ${DB_CONTAINER_NAME} --link ${DB_CONTAINER_NAME}:oracle-database -e PASS=SomePassWorD sath89/apex install
```

**Comment by liuxiaopiao** [comment]
Thanks @MaksymBilenko. But I don't want apex 5.0.2 and we need apex 4.2.6.

**Comment by MaksymBilenko** [comment]
I've created branch for you: https://github.com/MaksymBilenko/docker-oracle-apex/tree/4.2.6
`docker run -it --rm --volumes-from ${DB_CONTAINER_NAME} --link ${DB_CONTAINER_NAME}:oracle-database sath89/apex:4.2.6 install`

**Comment by liuxiaopiao** [comment]
Thank you so much @MaksymBilenko. I will try it!

**Comment by MaksymBilenko** [comment]
@liuxiaopiao Please share how it works for you. thank you

**Comment by liuxiaopiao** [comment]
It works well. Thank you so much @MaksymBilenko.
