### ISSUE TITLE
tnsnames.ora %hostname% and %port%

### ISSUE THREAD

**Issue by ddelpero** [MaksymBilenko/docker-oracle-xe-11g#9]
Hi, thanks for putting this docker image together. I have a problem with the tnsnames.ora file. I see it's setup with %hostname% and %port%. Is the tnsnames.ora file supposed to be automatically updated so these match the current host and port for Oracle? Is there a way to update this file every time the docker container is started?

**Comment by MaksymBilenko** [comment]
@ddelpero it already updates every time when you start database
